/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    App: typeof import('./src/components/nb-payments/src/App.vue')['default']
    ControlNbCreditCardText: typeof import('./src/components/nb-payments/ControlNbCreditCardText.vue')['default']
    ControlNbGradientText: typeof import('./src/components/nb-gradient-text/ControlNbGradientText.vue')['default']
    ControlNbHighlightSelectedText: typeof import('./src/components/nb-gradient-text/ControlNbHighlightSelectedText.vue')['default']
    ControlVgGradientText: typeof import('./src/components/nb-gradient-text/ControlVgGradientText.vue')['default']
    copy: typeof import('./src/components/nb-gradient-text/NbGradientText.story copy.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    NbCreditCard: typeof import('./../../packages/vue-components/nb-payments/src/components/NbCreditCard.vue')['default']
    'NbCreditCard.story': typeof import('./src/components/nb-payments/NbCreditCard.story.vue')['default']
    NbCreditCardCards: typeof import('./../../packages/vue-components/nb-payments/src/components/NbCreditCardCards.vue')['default']
    NbGradientText: typeof import('./../../packages/vue-components/nb-text/src/components/NbGradientText.vue')['default']
    'NbGradientText.story': typeof import('./src/components/nb-gradient-text/NbGradientText.story.vue')['default']
    NbHighlightSelectedText: typeof import('./../../packages/vue-components/nb-text/src/components/NbHighlightSelectedText.vue')['default']
    'NbHighlightSelectedText.story': typeof import('./src/components/nb-gradient-text/NbHighlightSelectedText.story.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'VgGradientText.story': typeof import('./src/components/VgGradientText/VgGradientText.story.vue')['default']
  }
}
