/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NbCreditCard: typeof import('./../../packages/vue-components/nb-payments/src/components/NbCreditCard.vue')['default']
    NbCreditCardCards: typeof import('./../../packages/vue-components/nb-payments/src/components/NbCreditCardCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
