/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ControlNbButtonMechanical: typeof import('./src/components/nb-buttons/ControlNbButtonMechanical.vue')['default']
    ControlNbCreditCard: typeof import('./src/components/nb-payments/ControlNbCreditCard.vue')['default']
    ControlNbGradientText: typeof import('./src/components/nb-gradient-text/ControlNbGradientText.vue')['default']
    ControlNbHighlightSelectedText: typeof import('./src/components/nb-gradient-text/ControlNbHighlightSelectedText.vue')['default']
    NbButtonMechanical: typeof import('./../../packages/vue-components/nb-buttons/src/components/NbButtonMechanical.vue')['default']
    'NbButtonMechanical.story': typeof import('./src/components/nb-buttons/NbButtonMechanical.story.vue')['default']
    NbCreditCard: typeof import('./../../packages/vue-components/nb-payments/src/components/NbCreditCard.vue')['default']
    'NbCreditCard.story': typeof import('./src/components/nb-payments/NbCreditCard.story.vue')['default']
    NbCreditCardCards: typeof import('./../../packages/vue-components/nb-payments/src/components/NbCreditCardCards.vue')['default']
    NbGradientText: typeof import('./../../packages/vue-components/nb-text/src/components/NbGradientText.vue')['default']
    'NbGradientText.story': typeof import('./src/components/nb-gradient-text/NbGradientText.story.vue')['default']
    NbHighlightSelectedText: typeof import('./../../packages/vue-components/nb-text/src/components/NbHighlightSelectedText.vue')['default']
    'NbHighlightSelectedText.story': typeof import('./src/components/nb-gradient-text/NbHighlightSelectedText.story.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
